# Ejercicios Resueltos

In [1]:
import numpy as np

### Ejercicio 1

Cree una muestra de puntos que sigan la ecuación $Y = AX + B$, donde A = 2.5 y B = 20.

In [5]:
x = np.random.rand(100)
y = 2.5 * x + 20

### Ejercicio 2

Representa la función logística o sigmoidea entre -20 y 20. Recuerda que su fórmula es:

$$\displaystyle S (x) = {\frac {1}{1+e^{-x}}} = {\frac {e^{x}}{e^{x}+1}}$$

_Hint_: revisa la función np.exp

- Metodo 1

In [9]:
x = np.linspace(-20,20,100)
y = np.exp(x) / (np.exp(x) + 1)

- Metodo 2

In [10]:
x = np.linspace(-20,20,100)

def sigmoidea(m):
    return np.exp(x) / (np.exp(x) + 1)

y = sigmoidea(x)

### Ejercicio 3

En una granja de pollos y conejos hay 35 cabezas y 94 patas. ¿Cuántos pollos y cuántos conejos tenemos?

Recuerda:

$$A \cdot X = B$$

$$A^{-1} \cdot A \cdot X = I \cdot X = A^{-1} \cdot B$$

$$X = A^{-1} \cdot B$$

Planetando el ejercicio:

$p + c = 35$

$2p +4c = 94$

- Metodo 1

In [20]:
B = np.array([35,94])

A_prev = [1,1,2,4]
A = np.array(a_prev).reshape(2,2)
A_pos = np.mat(A)
A_inv = A_pos.I
A_inv

x = A_inv.dot(B)
x

matrix([[23., 12.]])

- Metodo 2

In [21]:
B = np.array([35,94])

A_prev = [1,1,2,4]
A = np.array(a_prev).reshape(2,2)

In [22]:
from numpy import linalg as la

In [23]:
A_inv = la.inv(A)
A_inv

x = A_inv.dot(B)
x

array([23., 12.])

In [40]:
a[0:2,]

array([[-44.,  12.],
       [ 12.,  51.]])

### Ejercicio 4

In [42]:
lista_de_listas=[ [-44,12], 
                  [12.0,51], 
                  [1300, -5.0]]
a = np.array(lista_de_listas)
a

# Restarle 5 a la fila 2 de la matriz
#IMPLEMENTAR

a[2,] = a[2,] + 5
print(a)


# Multiplicar por 2 toda la matriz
#IMPLEMENTAR
a = a * 2
print(a)

# Dividir por -5 las dos primeras filas de la matriz
#IMPLEMENTAR
a[0:2,] = a[0:2,] / 5
print(a)


#Imprimir la ultima fila de la matriz
ultima_fila=0 # IMPLEMENTAR
ultima_fila = a[2,]
print(ultima_fila)

[[ -44.   12.]
 [  12.   51.]
 [1305.    0.]]
[[ -88.   24.]
 [  24.  102.]
 [2610.    0.]]
[[ -17.6    4.8]
 [   4.8   20.4]
 [2610.     0. ]]
[2610.    0.]


In [72]:
# Calcular la suma de los elementos de a utilizando dos fors anidados
suma = 0
#IMPLEMENTAR
for i in range(len(a)):
    for j in range(len(a[i])):
        suma = suma + a[i][j]
print(suma)

# Calcular la suma de los elementos de a utilizando np.sum
#IMPLEMENTAR
suma_2 = np.sum(a)
print(suma_2)

# Calcular el promedio de los elementos de las primeras dos filas de a
# utilizando dos fors anidados
entero = 0
promedio=0
suma=0
#IMPLEMENTAR
for i in range(len(a)):
    for j in range(len(a[i])):
        suma = suma + a[i][j]
        entero = entero + 1
        promedio = suma / entero
print(promedio)

# Calcular el promedio de los elementos de las primeras dos filas de utilizando slices y np.mean
#IMPLEMENTAR
promedio = np.mean(a)
print(promedio)

2658.4
2658.4
443.06666666666666
443.06666666666666
