# Libreria Numpy

Numpy, es el paquete más básico para trabajar con datos en Python.

El objeto más importante definido en Numpy es un tipo de matriz N-dimensional llamado "ndarray", en un objeto "ndarray" se puede almacenar varios elementos del mismo tipo de datos. Las facilidades del objeto matriz hace que Numpy sea tan conveniente para realizar manipulaciones de datos asimismo es muy útil para realizar operaciones matemáticas y lógicas en Arrays. Proporciona una gran cantidad de características útiles para operaciones en n-matrices y matrices en Python.

- Cada elemento en un "ndarray" toma el mismo tamaño de bloque en la memoria.
- Cada elemento en "ndarray" es un objeto de tipo objeto de datos (llamado dtype).
- Cada elemento extraído del objeto "ndarray" está representado por un objeto Python de uno de los tipos escalares de matriz.

    Instalación

Si tiene Anaconda, simplemente puede instalar Numpy desde su terminal o símbolo del sistema usando:

conda instalar numpy

Si no tiene Anaconda en su computadora, instale Numpy desde su terminal usando:

pip instalar numpy

    Trabajando con numpy

In [1]:
import numpy as np  #importa la libreria

- ndarray.ndim: el número de ejes (dimensiones) de la matriz.

- ndarray.shape: las dimensiones de la matriz. Esta es una tupla de enteros que indica el tamaño de la matriz en cada dimensión. Para una matriz con n filas y m columnas, la forma será (n, m).

- ndarray.size: el número total de elementos de la matriz.

- ndarray.dtype: un objeto que describe el tipo de los elementos en la matriz. Uno puede crear o especificar tipos de dtype usando tipos estándar de Python.

- ndarray.itemsize: el tamaño en bytes de cada elemento de la matriz. Por ejemplo, una matriz de elementos del tipo float64 tiene tamaño de elemento 8 (= 64/8), mientras que uno de tipo complex32 tiene tamaño de elemento 4 (= 32/8). Es equivalente a ndarray.dtype.itemsize.

In [12]:
a_list = [1, 2, 3, 4, 5]
a = np.array(my_list)
a  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [8]:
a.ndim

1

In [7]:
a.shape

(5,)

In [11]:
a.size

5

In [9]:
a.dtype

dtype('int64')

In [25]:
a.itemsize

8

In [14]:
type(a)

numpy.ndarray

In [15]:
b_list = [1.2, 3.5, 5.1]
b = np.array(b_list)
b

array([1.2, 3.5, 5.1])

In [17]:
b.dtype

dtype('float64')

Ejemplos

In [37]:
a = np.array([1,2,3,4,5])
b = np.array([(1.5,2,3), (4,5,6)])
c = np.array( [ [1,2], [3,4] ], dtype=complex )
d = np.array([1, 0, 10], dtype=bool)
e = np.array([1, 'a'], dtype='object') #Crea una matriz de objetos para contener números y cadenas.

In [22]:
a

array([1, 2, 3, 4, 5])

In [27]:
a.shape

(5,)

In [23]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [28]:
b.shape

(2, 3)

In [24]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [29]:
c.shape

(2, 2)

In [32]:
d

array([ True, False,  True])

In [31]:
d.shape

(3,)

In [38]:
e

array([1, 'a'], dtype=object)

In [39]:
e.shape

(2,)

Hay una serie de funciones de conveniencia para crear matrices especiales particulares.

In [42]:
print(np.zeros(10)) #zeros
print(np.ones((2,3))) #unos con dimensiones
print(np.ones_like(a)) #unos
print(np.eye(4)) #identidad
print(np.empty((2,3,2))) #complejo

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1 1]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[[4.64601527e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


In [49]:
from numpy import math    #importa "math"

In [43]:
print(np.arange(10)) #enteros ordenados
print(np.arange( 10, 30, 5 )) #funcion "seq"
print(np.arange( 0, 2 * np.math.pi, 0.3 )) #utilizando "math.pi"
print(np.linspace( 0, 2 * np.math.pi, 15 )) #15 numeros de 0 a 2*pi

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9 4.2 4.5 4.8 5.1
 5.4 5.7 6. ]
[0.         0.44879895 0.8975979  1.34639685 1.7951958  2.24399475
 2.6927937  3.14159265 3.5903916  4.03919055 4.48798951 4.93678846
 5.38558741 5.83438636 6.28318531]


Las matrices unidimensionales se imprimen como filas, los bidimensionales como matrices y los tridimensionales como listas de matrices.

In [48]:
a = np.arange(6)                         # 1d array
a

array([0, 1, 2, 3, 4, 5])

In [45]:
b = np.arange(12).reshape(4,3)           # 2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
c = np.arange(24).reshape(2,3,4)         # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

arrays y variables aleatorias

In [58]:
a = np.random.rand(10) #aleatorios entre 0 y 1
b = np.random.rand(5, 4) #aleatorios entre 0 y 1 con dimensiones

c = np.random.randn(10) #aleatorios con distribucion normal
d = np.random.randn(5, 4) #aleatorios con distribucion normal y con dimensiones

e = np.random.randint(10) #aleatorio entero
f = np.random.randint(2,20, size = 5) #aleatorios enteros entre 2 y 19 con tamaño 5 
g = np.random.randint(2,20, size = (5,4)) #aleatorios enteros entre 2 y 19 con dimensiones

In [62]:
a

array([0.12566689, 0.35368273, 0.66431947, 0.52834476, 0.25941899,
       0.62640948, 0.63604065, 0.7841002 , 0.56937522, 0.19131511])

In [63]:
b

array([[0.81644654, 0.22839645, 0.91455822, 0.34233659],
       [0.8124076 , 0.02086163, 0.18280901, 0.65448001],
       [0.87034608, 0.94560119, 0.32364283, 0.27134863],
       [0.38576163, 0.48831665, 0.82835321, 0.33443985],
       [0.4647369 , 0.99973101, 0.43647223, 0.15140175]])

In [64]:
c

array([ 0.86230692, -0.68471364,  0.7580935 , -2.39500364,  1.6160317 ,
        1.80641004,  0.2272208 ,  0.99311132,  0.43018487, -0.02453153])

In [65]:
d

array([[ 0.8168777 ,  1.20681675,  0.71963398, -0.32320042],
       [-0.17102882,  1.43333096, -1.53866204,  0.74213783],
       [ 0.52138006,  0.70387971,  1.12243537,  0.4777388 ],
       [-0.58794749, -1.50310743, -2.19602299, -1.9267791 ],
       [-0.02226343,  2.12933799, -0.31758289,  0.10869782]])

In [66]:
e

7

In [67]:
f

array([15, 11,  3,  7,  3])

In [68]:
g

array([[ 6,  9,  8, 10],
       [ 8, 11,  6,  4],
       [16,  9, 17, 10],
       [ 9, 19,  8,  5],
       [10, 13, 16,  2]])

### Indexing y Slicing

![Python slicing](https://infohost.nmt.edu/tcc/help/pubs/python/web/fig/slicing.png)

In [69]:
a[6]

0.6360406470383483

In [71]:
b[2][3]

0.27134862581407493

In [73]:
b[2,3]

0.27134862581407493

In [74]:
a[1:6]

array([0.35368273, 0.66431947, 0.52834476, 0.25941899, 0.62640948])

In [75]:
a[:]

array([0.12566689, 0.35368273, 0.66431947, 0.52834476, 0.25941899,
       0.62640948, 0.63604065, 0.7841002 , 0.56937522, 0.19131511])

In [86]:
a[::-1]

array([0.19131511, 0.56937522, 0.7841002 , 0.63604065, 0.62640948,
       0.25941899, 0.52834476, 0.66431947, 0.35368273, 0.12566689])

In [90]:
a[-1:]

array([0.19131511])

In [89]:
a[:-1]

array([0.12566689, 0.35368273, 0.66431947, 0.52834476, 0.25941899,
       0.62640948, 0.63604065, 0.7841002 , 0.56937522])

In [76]:
a[:4]

array([0.12566689, 0.35368273, 0.66431947, 0.52834476])

In [77]:
a[4:]

array([0.25941899, 0.62640948, 0.63604065, 0.7841002 , 0.56937522,
       0.19131511])

In [78]:
b[:2,:3]

array([[0.81644654, 0.22839645, 0.91455822],
       [0.8124076 , 0.02086163, 0.18280901]])

In [79]:
b[2:,:3]

array([[0.87034608, 0.94560119, 0.32364283],
       [0.38576163, 0.48831665, 0.82835321],
       [0.4647369 , 0.99973101, 0.43647223]])

In [80]:
b[:2,3:]

array([[0.34233659],
       [0.65448001]])

In [82]:
a > 0.5

array([False, False,  True,  True, False,  True,  True,  True,  True,
       False])

In [83]:
f[(f > 10) & (f % 3 == 0)]

array([15])

In [84]:
even_1 = f % 3 == 0
even_2 = f > 10
even_3 = even_1 & even_2

In [85]:
f[even_2]

array([15, 11])