# Libreria Numpy

Numpy, es el paquete más básico para trabajar con datos en Python.

El objeto más importante definido en Numpy es un tipo de matriz N-dimensional llamado "ndarray", en un objeto "ndarray" se puede almacenar varios elementos del mismo tipo de datos. Las facilidades del objeto matriz hace que Numpy sea tan conveniente para realizar manipulaciones de datos asimismo es muy útil para realizar operaciones matemáticas y lógicas en Arrays. Proporciona una gran cantidad de características útiles para operaciones en n-matrices y matrices en Python.

- Cada elemento en un "ndarray" toma el mismo tamaño de bloque en la memoria.
- Cada elemento en "ndarray" es un objeto de tipo objeto de datos (llamado dtype).
- Cada elemento extraído del objeto "ndarray" está representado por un objeto Python de uno de los tipos escalares de matriz.

### Instalación

Si tiene Anaconda, simplemente puede instalar Numpy desde su terminal o símbolo del sistema usando:

conda instalar numpy

Si no tiene Anaconda en su computadora, instale Numpy desde su terminal usando:

pip instalar numpy

## Trabajando con numpy

In [1]:
import numpy as np  #importa la libreria

- ndarray.ndim: el número de ejes (dimensiones) de la matriz.

- ndarray.shape: las dimensiones de la matriz. Esta es una tupla de enteros que indica el tamaño de la matriz en cada dimensión. Para una matriz con n filas y m columnas, la forma será (n, m).

- ndarray.size: el número total de elementos de la matriz.

- ndarray.dtype: un objeto que describe el tipo de los elementos en la matriz. Uno puede crear o especificar tipos de dtype usando tipos estándar de Python.

- ndarray.itemsize: el tamaño en bytes de cada elemento de la matriz. Por ejemplo, una matriz de elementos del tipo float64 tiene tamaño de elemento 8 (= 64/8), mientras que uno de tipo complex32 tiene tamaño de elemento 4 (= 32/8). Es equivalente a ndarray.dtype.itemsize.

### Creación de arrays

In [3]:
a_list = [1, 2, 3, 4, 5]
a = np.array(a_list)
a  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

In [4]:
a.ndim

1

In [5]:
a.shape

(5,)

In [6]:
a.size

5

In [7]:
a.dtype

dtype('int64')

In [8]:
a.itemsize

8

In [9]:
type(a)

numpy.ndarray

In [10]:
b_list = [1.2, 3.5, 5.1]
b = np.array(b_list)
b

array([1.2, 3.5, 5.1])

In [11]:
b.dtype

dtype('float64')

Ejemplos

In [12]:
a = np.array([1,2,3,4,5])
b = np.array([(1.5,2,3), (4,5,6)])
c = np.array( [ [1,2], [3,4] ], dtype=complex )
d = np.array([1, 0, 10], dtype=bool)
e = np.array([1, 'a'], dtype='object') #Crea una matriz de objetos para contener números y cadenas.

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
a.shape

(5,)

In [15]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
b.shape

(2, 3)

In [17]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
c.shape

(2, 2)

In [19]:
d

array([ True, False,  True])

In [20]:
d.shape

(3,)

In [21]:
e

array([1, 'a'], dtype=object)

In [22]:
e.shape

(2,)

### Funciones para crear matrices especiales.

In [23]:
print(np.zeros(10)) #zeros
print(np.ones((2,3))) #unos con dimensiones
print(np.ones_like(a)) #unos
print(np.eye(4)) #identidad
print(np.empty((2,3,2))) #complejo

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1 1]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[[4.66692861e-310 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


In [24]:
from numpy import math    #importa "math"

In [25]:
print(np.arange(10)) #enteros ordenados
print(np.arange( 10, 30, 5 )) #funcion "seq"
print(np.arange( 0, 2 * np.math.pi, 0.3 )) #utilizando "math.pi"
print(np.linspace( 0, 2 * np.math.pi, 15 )) #15 numeros de 0 a 2*pi

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9 4.2 4.5 4.8 5.1
 5.4 5.7 6. ]
[0.         0.44879895 0.8975979  1.34639685 1.7951958  2.24399475
 2.6927937  3.14159265 3.5903916  4.03919055 4.48798951 4.93678846
 5.38558741 5.83438636 6.28318531]


Las matrices unidimensionales se imprimen como filas, los bidimensionales como matrices y los tridimensionales como listas de matrices.

In [26]:
a = np.arange(6)                         # 1d array
a

array([0, 1, 2, 3, 4, 5])

In [27]:
b = np.arange(12).reshape(4,3)           # 2d array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
c = np.arange(24).reshape(2,3,4)         # 3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Arrays y variables aleatorias

In [29]:
a = np.random.rand(10) #aleatorios entre 0 y 1
b = np.random.rand(5, 4) #aleatorios entre 0 y 1 con dimensiones

c = np.random.randn(10) #aleatorios con distribucion normal
d = np.random.randn(5, 4) #aleatorios con distribucion normal y con dimensiones

e = np.random.randint(10) #aleatorio entero
f = np.random.randint(2,20, size = 5) #aleatorios enteros entre 2 y 19 con tamaño 5 
g = np.random.randint(2,20, size = (5,4)) #aleatorios enteros entre 2 y 19 con dimensiones

In [30]:
a

array([0.73027849, 0.09384367, 0.36705701, 0.25010242, 0.56645088,
       0.72432896, 0.56296666, 0.58114649, 0.59992745, 0.24846207])

In [31]:
b

array([[0.9018337 , 0.29911775, 0.45004778, 0.12320981],
       [0.35131591, 0.1136663 , 0.08627416, 0.98566399],
       [0.76173804, 0.4430825 , 0.08585352, 0.04145551],
       [0.95518781, 0.74951804, 0.7199875 , 0.63265396],
       [0.29355254, 0.30052231, 0.57672745, 0.02526211]])

In [32]:
c

array([ 0.55996854,  0.7380365 ,  0.79786222, -0.53950456,  1.13426342,
        1.33279209, -0.10929581, -1.42858319, -0.38786942,  1.48176529])

In [33]:
d

array([[-0.63924771,  0.01622111,  0.45676564, -2.35287413],
       [ 1.26469902, -1.73059506,  1.85147083, -1.21311938],
       [ 0.13859659,  1.53602185, -0.85504579,  0.59685184],
       [-0.29668331, -0.55724001,  1.25112444, -0.55281376],
       [-1.4842558 ,  2.84511055, -0.64698651, -0.09263851]])

In [34]:
e

4

In [35]:
f

array([17, 17, 12,  8,  4])

In [36]:
g

array([[ 6, 15,  8,  3],
       [ 2,  2, 18, 14],
       [ 3,  4,  7,  9],
       [ 8,  8,  7, 12],
       [10, 13, 11, 11]])

### Indexing y Slicing

![Python slicing](https://infohost.nmt.edu/tcc/help/pubs/python/web/fig/slicing.png)

In [37]:
a[6]

0.562966662908494

In [38]:
b[2][3]

0.041455505729046216

In [39]:
b[2,3]

0.041455505729046216

In [40]:
a[1:6]

array([0.09384367, 0.36705701, 0.25010242, 0.56645088, 0.72432896])

In [41]:
a[:]

array([0.73027849, 0.09384367, 0.36705701, 0.25010242, 0.56645088,
       0.72432896, 0.56296666, 0.58114649, 0.59992745, 0.24846207])

In [42]:
a[::-1]

array([0.24846207, 0.59992745, 0.58114649, 0.56296666, 0.72432896,
       0.56645088, 0.25010242, 0.36705701, 0.09384367, 0.73027849])

In [43]:
a[-1:]

array([0.24846207])

In [44]:
a[:-1]

array([0.73027849, 0.09384367, 0.36705701, 0.25010242, 0.56645088,
       0.72432896, 0.56296666, 0.58114649, 0.59992745])

In [45]:
a[:4]

array([0.73027849, 0.09384367, 0.36705701, 0.25010242])

In [46]:
a[4:]

array([0.56645088, 0.72432896, 0.56296666, 0.58114649, 0.59992745,
       0.24846207])

In [47]:
b[:2,:3]

array([[0.9018337 , 0.29911775, 0.45004778],
       [0.35131591, 0.1136663 , 0.08627416]])

In [48]:
b[2:,:3]

array([[0.76173804, 0.4430825 , 0.08585352],
       [0.95518781, 0.74951804, 0.7199875 ],
       [0.29355254, 0.30052231, 0.57672745]])

In [49]:
b[:2,3:]

array([[0.12320981],
       [0.98566399]])

In [50]:
a > 0.5

array([ True, False, False, False,  True,  True,  True,  True,  True,
       False])

In [51]:
f[(f > 10) & (f % 3 == 0)]

array([12])

In [52]:
even_1 = f % 3 == 0
even_2 = f > 10
even_3 = even_1 & even_2

In [53]:
f[even_2]

array([17, 17, 12])

### Operaciones con arrays

In [58]:
a = np.array([10,20,30,40,50])
b = np.arange(5)

c = a - b
c

array([10, 19, 28, 37, 46])

In [59]:
b ** 2

array([ 0,  1,  4,  9, 16])

In [60]:
10 * np.cos(a)  # funcion coseno

array([-8.39071529,  4.08082062,  1.5425145 , -6.66938062,  9.64966028])

In [103]:
d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
e = np.arange(12).reshape(4,3)

d * e  # ambos arrays deben tener la misma dimension y elementos

array([[  0,   2,   6],
       [ 12,  20,  30],
       [ 42,  56,  72],
       [ 90, 110, 132]])

In [112]:
f = np.arange(12).reshape(3,4)

d.dot(f)  # ambos arrays deben tener la misma dimension y elementos invertidos

array([[ 32,  38,  44,  50],
       [ 68,  83,  98, 113],
       [104, 128, 152, 176],
       [140, 173, 206, 239]])

In [113]:
d @ f  # ambos arrays deben tener la misma dimension y elementos invertidos

array([[ 32,  38,  44,  50],
       [ 68,  83,  98, 113],
       [104, 128, 152, 176],
       [140, 173, 206, 239]])

Algunas operaciones, como "+=" y "*=", actúan en su lugar para modificar una matriz existente en lugar de crear una nueva

In [116]:
a *=3
a

array([ 90, 180, 270, 360, 450])

In [119]:
b += a
b

array([180, 361, 542, 723, 904])

In [122]:
c = np.array([1,2,3])
d = np.exp(c)  # funcion exponencial
d

array([ 2.71828183,  7.3890561 , 20.08553692])

In [123]:
d.sum()

30.19287485057736

In [124]:
d.min()

2.718281828459045

In [125]:
d.max()

20.085536923187668

In [130]:
e = np.arange(12).reshape(4,3)
e

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [131]:
e.sum(axis = 0)

array([18, 22, 26])

In [127]:
e.sum(axis = 1)

array([ 3, 12, 21, 30])

In [133]:
e.cumsum(axis = 0) # suma acumulativa

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]])

In [137]:
e.cumprod(axis = 0)  # producto acumulativo

array([[  0,   1,   2],
       [  0,   4,  10],
       [  0,  28,  80],
       [  0, 280, 880]])

In [136]:
f = np.sqrt(e)  # funcion raiz cuadrada
f

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [139]:
f.transpose()  # transpuesta de la matriz

array([[0.        , 1.73205081, 2.44948974, 3.        ],
       [1.        , 2.        , 2.64575131, 3.16227766],
       [1.41421356, 2.23606798, 2.82842712, 3.31662479]])

In [141]:
g = np.mat(e)
g

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [150]:
g.T  # inversa de la matriz

matrix([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [149]:
g[:2,:2].I  # inversa de la matriz cuadrada

matrix([[-1.33333333,  0.33333333],
        [ 1.        ,  0.        ]])

### Algebra lineal con numpy

In [151]:
from numpy import linalg as la

In [156]:
e

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [171]:
np.trace(e) # calcula la traza de la matriz cuadrada

12

In [163]:
np.trace(e,offset = 1)  # desplazamiento de la diagonal en 1

6

In [162]:
np.trace(e, offset = -1)  # desplazamiento de la diagonal en -1

21

In [172]:
f = e[:2,:2]
f

array([[0, 1],
       [3, 4]])

In [173]:
la.det(f)  # calcula la determinante de la matriz cuadrada

-3.0000000000000004

In [174]:
la.inv(f)  # calcula la inversa de la matriz cuadrada

array([[-1.33333333,  0.33333333],
       [ 1.        ,  0.        ]])

In [179]:
a = np.array([1,1,1])
a

array([1, 1, 1])

In [180]:
la.norm(a)  # calcula la norma del vector

1.7320508075688772

In [181]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [190]:
print(b)
print(la.norm(b))
print(la.norm(b,2))  
print(la.norm(b,'fro'))  
print(la.norm(b.reshape(4),2))  
print(la.norm(b,1))  
print(la.norm(b,np.inf))  
print(la.norm(b,-np.inf))

[[1 2]
 [3 4]]
5.477225575051661
5.464985704219043
5.477225575051661
5.477225575051661
6.0
7.0
3.0


In [193]:
c = np.arange(1,4)
c

array([1, 2, 3])

In [194]:
print(c)
print(la.norm(c))
print(la.norm(c,2))
print(la.norm(c,1))
print(la.norm(c,np.inf))
print(la.norm(c,-np.inf))

[1 2 3]
3.7416573867739413
3.7416573867739413
6.0
3.0
1.0
